### ISSUE TITLE
deployment property in azure.yaml should be removed

### ISSUE THREAD

**Issue by howieleung** [microsoft/Conversation-Knowledge-Mining-Solution-Accelerator#353]
# Describe the bug
In azure .yaml, I found

```
deployment:
  mode: Incremental
  template: ./infra/main.bicep  # Path to the main.bicep file inside the 'deployment' folder
  parameters:
    solutionPrefix: ${parameters.solutionPrefix}
    otherLocation: ${parameters.otherLocation}
    baseUrl: ${parameters.baseUrl}

```

This doesn't do anything and confuse people.   It isn't consumed by azd up and also not described in azure.yaml schema.   Please remove it.
